### ISSUE TITLE
您好，请问代码什么时候能够开源，谢谢~

### ISSUE THREAD

**Issue by Victarry** [daooshee/CompoundVST#1]

**Comment by daooshee** [comment]
Hi, thank you for your interest in our work. Sorry that since we are working on an extension, we are not going to release the code at least recently. 

If you want to run comparisons for your paper, you can email me the testing videos and I can run the results for you. If you want to build our model, you can email me if you have problems with implementation details.

Finally thank you again for your interest in our work.

**Comment by daooshee** [comment]
Hi, the code of our extension work, Consistent Video Style Transfer via Relaxation and Regularization (TIP 2020), is available on: [https://github.com/daooshee/ReReVST-Code](https://github.com/daooshee/ReReVST-Code). In the extension work, we propose a new relaxed style loss, which further improves the performance. You can refer to [https://daooshee.github.io/ReReVST/](https://daooshee.github.io/ReReVST/) for more information.
